In [8]:
import streamlit as st
import pandas as pd
import numpy as np
import time

import matplotlib.pyplot as plt # plotting library
import seaborn as sns # pretty plotting

sns.set(rc={'figure.figsize':(20,10)})

from sklearn.linear_model import LinearRegression # linear regression package
from sklearn.model_selection import train_test_split # split dataset

from sklearn.linear_model import Lasso

from sklearn.linear_model import Ridge

from sklearn.metrics import mean_squared_error as mse

In [10]:
# insurance_df = pd.read_csv('insurance_regression.csv')
insurance_df = pd.read_csv('insurance_regression.csv').reset_index()

insurance_df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'insurance_regression.csv'

In [11]:
columns = ['age','sex', 'bmi', 'children', 'smoker', 'region']
target = ['charges']

X = insurance_df[columns]
y = insurance_df[target]

X_dummies = pd.get_dummies(X)

X_final = X_dummies.drop(['sex_male', 'smoker_no'], axis=1)

X_final.head()

NameError: name 'insurance_df' is not defined

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size = 0.3, random_state = 42)

NameError: name 'X_final' is not defined

In [12]:
model = LinearRegression() 

In [13]:
model.fit(X_train, y_train)

LinearRegression()

In [27]:
print(model.score(X_test, y_test))

0.7696118054369008


In [13]:
import joblib

In [29]:
# saving the model
filename = 'finalized_model.sav'
joblib.dump(model, filename)

['finalized_model.sav']

In [30]:
loaded_model = joblib.load(filename)

In [31]:
loaded_model.predict(X_test)

array([[ 9.01636753e+03],
       [ 7.01997635e+03],
       [ 3.68708343e+04],
       [ 9.51853774e+03],
       [ 2.69740308e+04],
       [ 1.10808462e+04],
       [-4.06177600e+01],
       [ 1.71922331e+04],
       [ 9.74950536e+02],
       [ 1.13299594e+04],
       [ 2.80574861e+04],
       [ 9.47838799e+03],
       [ 4.98095281e+03],
       [ 3.84564701e+04],
       [ 4.03433327e+04],
       [ 3.71038753e+04],
       [ 1.51982019e+04],
       [ 3.57689693e+04],
       [ 8.88568387e+03],
       [ 3.13835989e+04],
       [ 3.79641903e+03],
       [ 1.02628964e+04],
       [ 2.37593679e+03],
       [ 7.26280819e+03],
       [ 1.12875675e+04],
       [ 1.31383480e+04],
       [ 1.46241614e+04],
       [ 6.07324604e+03],
       [ 1.00361537e+04],
       [ 1.97927814e+03],
       [ 9.07103928e+03],
       [ 1.31369887e+04],
       [ 4.30868680e+03],
       [ 3.21105955e+03],
       [ 4.48957162e+03],
       [ 1.33774493e+04],
       [ 1.82221028e+03],
       [ 8.79191682e+03],
       [ 3.3

In [14]:
# get coefficients
coefficient = model.coef_

# get intercept
intercept = model.intercept_

In [15]:
coefficient

array([[  261.29692414,   348.90691516,   424.11912829,  -104.81182299,
        23628.36722236,   596.05658924,   109.12197876,  -374.91224933,
         -330.26631867]])

In [16]:
intercept

array([-12865.20866928])

In [18]:
model.score(X_final, y)

0.7506272930769431

In [19]:
y_predicted = model.predict(X_test)

In [24]:
# put coefficients into dataframe
# pair the feature names with the coefficients
coefficients_pd = pd.DataFrame((list(zip(columns, model.coef_ * 1000))), columns = ['Features', 'Coefficients'])

# print table of coefficients for contribution chart
coefficients_pd

Features                                       Coefficients
0      age  [261296.92414191976, 348906.91516017495, 42411...

In [25]:
coefficients_pd.sort_values('Coefficients').set_index('Features').plot(kind = 'barh', color = 'g')

TypeError: no numeric data to plot

In [26]:
# We input new advertising data into the model to predict future sales

# Sample TV, Radio, Newspaper
new_data = [[10, 30, 100]]
model.predict(new_data)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 9 is different from 3)

In [14]:
!pip install pipreqs

In [16]:
!pipreqs